version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: philophilo/py-tf-aws
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
        environment:
          AWS_SECRET_KEY: $AWS_SECRET_KEY
          AWS_ACCESS_KEY: $AWS_ACCESS_KEY
          AWS_REGION: $AWS_REGION
          PRODUCT: $PRODUCT
          ENV_NAME: $ENV_NAME
    steps:
      - checkout
      - run:
          command: |
            mkdir ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id = ${AWS_SECRET_KEY}" >> ~/.aws/credentials
            echo "aws_secret_access_key = ${AWS_ACCESS_KEY}" >> ~/.aws/credentials
            echo "[default]" >> ~/.aws/config
            echo "region =${AWS_REGION}" >> ~/.aws/config
            nosetests
            echo "output = json" >> ~/.aws/config
            echo "env_name   = \"${ENV_NAME}\"" > terraform.tfvars
            echo "product    = \"${PRODUCT}\"" >> terraform.tfvars
            echo "aws_region = \"${AWS_REGION}\"" >> terraform.tfvars
            echo "---------------"
            terraform init
            terraform plan
